// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpwgkjqifdbwecyuimuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwd2dranFpZmRid2VjeXVpbXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTIxMjMsImV4cCI6MjA3MTk2ODEyM30.ILhO4vYFy_DOKYEmvOEUCi81pq0C21TeIi_LX4CYDO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});